### ISSUE TITLE
Several cookies to expire

### ISSUE THREAD

**Issue by nullwriter** [DASPRiD/Helios#3]
Hi,

Is there no way to expire several cookies instead of just ONE?

**Comment by DASPRiD** [comment]
Do you mean removing cookies not related to Helios?

**Comment by nullwriter** [comment]
I mean, I have 2 cookies being created by Helios, but only one can be removed at a time. I could remove them with a normal php `setcookie('cookie-name', '', time() - 3600);`, but is there a solution with Helios to expire several cookies instead of just one?

**Comment by DASPRiD** [comment]
Two cookies? How exactly did you do that? :)

**Comment by nullwriter** [comment]
Well, its a design for a website where we store the 'lab location' as well as the authorization on two different cookies. Once user logs out, it should flush all cookies.

**Comment by DASPRiD** [comment]
Well, I'm sure that you aren't setting that lab location cookie via Helios but some other means? You should just use FigCookies directly to expire that one.

**Comment by nullwriter** [comment]
Alright man 👍 thank you
